core/urls.py
from django.urls import path
from .views import (
    home_view,
    get_back,
    RequestSummary,
    FlightOccas,
    add_vol_occas_view,
    valid_company,
    AddVolOccas,
    valid_date,
    agent_flight_summary,
    post_vol,
    valid_services,
    validReleveTouchee,
    facturation_occas,
    CompaniesSummary,
    add_company,
    ValidNewCompany,
    valid_new_company_name,
    CompanyDetail,
    valid_fiche,
    price_list,
    price_list_actual,
    ValidPriceList,
    FichesTouchee,
    gestion_affect_fiches,
    AddQuota,
    valid_affect_quota,
    HistQuota,
    AffectQuota,
    valid_escale,
    HistAffect,
    valid_cnl_fiche,
    CNLFiches,
    HistCNL,
    valid_uniq_flt,
    add_schedule,
    NewSchedule,
    FactRegular,
    valid_company_fact,
    dashboard,
    build_chart,
    HistRegularFact,
    validFactRegular,
    FactRegularDetail,
    HistOPCompany,
    luggage_view,
    add_ahl, add_dpr, add_ohd,
    validBagCase,
    BagCaseDetails,
    valid_case,
    HistIndemn,
    AllPriceList,
    ExchangeRates,
    validExchRate,
    fact_regular_bill,
    Dash,
    cas_build_pie_chart,
    cas_build_time_chart,
)

app_name = 'core'

urlpatterns = [
    path('', home_view, name='home-view'),
    path('get-back', get_back, name = 'get-back'),
    path('request-summary/<str:activite>/', RequestSummary.as_view(), name = 'request-summary'),
    path('request-summary/<str:activite>/<str:qs>/', RequestSummary.as_view(), name = 'request-summary-specials'),
    path('flight-detail/<slug>/', FlightOccas.as_view(), name = 'flight-detail'),
    path('add-occas-flight/', add_vol_occas_view, name = 'add-occas-flight'),
    path('valid-company/', valid_company, name = 'valid-company'),
    path('valid-date/', valid_date, name = 'valid-date'),
    path('valid-vol-occas/', AddVolOccas.as_view(), name = 'valid-vol-occas'),
    path('agent-summary/<str:activite>/', agent_flight_summary.as_view(), name='agent-summary'),
    path('post-vol/<slug>/', post_vol.as_view(), name = 'post-vol'),
    path('valid-services/', valid_services, name = 'valid-services'),
    path('valid-releve-touchee/', validReleveTouchee.as_view(), name = 'valid-releve-touchee'),
    path('facturation-occas/<int:n_field>/', facturation_occas, name = 'facturation-occas'),
    path('companies-summary/', CompaniesSummary.as_view(), name = 'companies-summary'),
    path('add-company/', add_company, name = 'add-company'),
    path('valid-new-company/', ValidNewCompany.as_view(), name = 'valid-new-company'),
    path('valid-new-company-name/', valid_new_company_name, name = 'valid-new-company-name'),
    path('compagnie-detail/<slug>/', CompanyDetail.as_view(), name = 'compagnie-detail'),
    path('valid-fiche/', valid_fiche, name = 'valid-fiche'),
    path('price-list/<pk>/', price_list.as_view(), name = 'price-list'),
    path('price-list/', price_list_actual, name = 'price-list-actual'),
    path('annuaire-prices-list/', AllPriceList.as_view(), name = 'annuaire-prices-list'),
    path('valid-price-list/', ValidPriceList.as_view(), name = 'valid-price-list'),
    path('fiche-touchee/', FichesTouchee.as_view(), name = 'fiche-touchee'),
    path('fiche-touchee/gestion-fiches/', gestion_affect_fiches, name = 'gestion-fiches'),
    path('fiche-touchee/gestion-fiches/add-quota/', AddQuota.as_view(), name = 'add-quota'),
    path('valid-affect-quota/', valid_affect_quota, name = 'valid-affect-quota'),
    path('fiche-touchee/gestion-fiches/hist-quota/', HistQuota.as_view(), name = 'hist-quota'),
    path('affect-quota/', AffectQuota.as_view(), name = 'affect-quota'),
    path('valid-escale/', valid_escale, name = 'valid-escale'),
    path('fiche-touchee/gestion-fiches/hist-affect/', HistAffect.as_view(), name = 'hist-affect'),
    path('valid-cnl-fiche/', valid_cnl_fiche, name = 'valid-cnl-fiche'),
    path('fiche-touchee/gestion-fiches/cnl-fiches/', CNLFiches.as_view(), name = 'cnl-fiches'),
    path('fiche-touchee/gestion-fiches/hist-cnl/', HistCNL.as_view(), name = 'hist-cnl'),
    path('valid-uniq-flt/', valid_uniq_flt, name = 'valid-uniq-flt'),
    path('add-schedule/', add_schedule, name = 'add-schedule'),
    path('new-schedule/', NewSchedule.as_view(), name = 'new-schedule'),
    path('fact-regular/', FactRegular.as_view(), name = 'fact-regular'),
    path('valid-company-fact/', valid_company_fact, name = 'valid-company-fact'),
    path('dashboard/', dashboard, name = 'dashboard'),
    path('dashboard-cas/', Dash, name = 'dashboard-cas'),
    path('dashboard/build-chart/', build_chart, name = 'build-chart'),
    path('fact-regular/hist-regular-fact/', HistRegularFact.as_view(), name = 'hist-regular-fact'),
    path('valid-fact-regular/', validFactRegular.as_view(), name = 'valid-fact-regular'),
    path('fact-regular-detail/<slug>/', FactRegularDetail.as_view(), name = 'fact-regular-detail'),
    path('compagnie-detail/<slug>/historic-operations-company/', HistOPCompany.as_view(), name = 'historic-operations-company'),
    path('luggage-summary/<str:opt>/', luggage_view.as_view(), name = 'luggage-view'),
    path('luggage-view/add-ahl/', add_ahl, name = 'add-ahl'),
    path('luggage-view/add-dpr/', add_dpr, name = 'add-dpr'),
    path('luggage-view/add-ohd/', add_ohd, name = 'add-ohd'),
    path('bag-case/<pk>/', BagCaseDetails.as_view(), name = 'bag-case-details'),
    path('valid-bag-case/', validBagCase.as_view(), name = 'valid-bag-case'),
    path('valid-case/', valid_case, name = 'valid-case'),
    path('bag-case/<pk>/historique-des-propositions/', HistIndemn.as_view(), name = 'historique-des-propositions'),
    path('exchange-rates/', ExchangeRates.as_view(), name = 'exchange-rates'),
    path('valid-exchange-rate/', validExchRate.as_view(), name = 'valid-exchange-rate'),
    path('fact-regular-bill/<int:id>/', fact_regular_bill.as_view(), name = 'fact-regular-bill'),
    path('cas-build-pie-chart/', cas_build_pie_chart, name = 'cas-build-pie-chart'),
    path('cas-build-time-chart/', cas_build_time_chart, name = 'cas-build-time-chart'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('allauth.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>A | H - {% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'core/css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/mdb.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <!-- <link rel="stylesheet" href="{% static 'core/uikit-3.7.0/css/uikit.css' %}"> -->
    <!-- <link rel="stylesheet" href="{% static 'core/uikit-3.7.0/css/uikit-rtl.css' %}"> -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
    <script src="{% static 'core/js/mdb.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'core/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'core/uikit-3.7.0/js/uikit.js' %}" type="text/javascript"></script>
    <script src="{% static 'core/uikit-3.7.0/js/uikit-icons.js' %}" type="text/javascript"></script>
    <link rel="stylesheet" href="{% static 'core/style.css' %}">
    <!-- Custom JS -->
    <script src="{% static 'core/main.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'core/DataTables/datatables.css' %}"/>
    <script type="text/javascript" src="{% static 'core/DataTables/datatables.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/gh/loadingio/ldbutton@v1.0.1/dist/ldbtn.min.css"/>
    <script src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.flash.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/fixedcolumns/3.3.3/js/dataTables.fixedColumns.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/b-1.7.1/b-html5-1.7.1/datatables.min.css"/>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/b-1.7.1/b-html5-1.7.1/datatables.min.js"></script>
    <script type="text/javascript" src="{% static 'core/Stuk-jszip-b7f472d/dist/jszip.js' %}"></script>
  </head>
  <body>
    <script>
      function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    
    var csrftoken = getCookie('csrftoken');
    
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
    </script>
    {% include "main/navbar.html" %}

    <div class="bg"></div>

    <div id="" class="container mx-auto mh-100">
      <div id="message" class="mt-2 pb-0 pt-0" style="display: none;">
        <div id="alert" class="alert alert-dismissible fade show" role="alert">
        </div>
      </div>

      {% block content %}
      {% endblock content  %}
    </div>

    {% block extra_body %}
    {% endblock %}

    {% include "main/footer.html" %}
    
    
  </body>
  
</html> 

templates/main/footer.html
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted mt-5" style="color: white !important; background-color: #2c2c2c !important;">
    <!-- Section: Links  -->
    <!--  -->
  
    <!-- Copyright -->
    <div class="text-center mb-5" style="background-color: #F9FAFB !important; color: #0e385b !important; padding-left: 10% !important; padding-right: 10% !important;">
      <hr style="color: #4e4e4e !important; height: 1px !important;">
      © 2021 Copyright:
      <a class="text-reset fw-bold">BELARIBI & BACHOUNDA</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

templates/main/navbar.html
{% load static %}
{% load cart_template_tags %} 
<nav id='navbar_1' class="navbar navbar-expand-lg px-5 py-1 " style="background-color: #0e385b !important;">
  <style>
      @font-face {
      font-family: 'Ubuntu-Medium';
        src: local('Ubuntu'),
            url("{% static 'core/font/Ubuntu/Ubuntu-Regular.ttf' %}");
      }
    </style>
  <a class="navbar-brand" href="{% url 'core:home-view' %}" style="font-weight: lighter !important; font-size: 2.85rem !important; color: white !important;">A H&nbsp;&nbsp; |&nbsp;<b class="font-weight-bold" style="margin-left: 15px !important; letter-spacing: 2px !important; color: white !important;">CENTER</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon" style="background-color: white !important;"></span>
  </button>
  
  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <b>
      <ul class="navbar-nav" style="font-family: 'Ubuntu-Medium' !important; font-size:medium !important;">
        {% if request.user.is_authenticated %}
        <li class="nav-item active ml-4">
          <div class="d-flex flex-row d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="#d2d2d2" class="bi bi-house-door-fill" viewBox="0 0 16 16">
              <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z"/>
            </svg>
            <a class="nav-link" style="color: white !important;" href="{% url 'core:home-view' %}">Acceuil <span class="sr-only">(current)</span></a>
          </div>
        </li>
        {% if request.user.profile.poste == 'SOUS DIRECTEUR GESTION DES ESCALES' %}
        <li class="nav-item ml-4">
          <div class="d-flex flex-row d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="#d2d2d2" class="bi bi-graph-up" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M0 0h1v15h15v1H0V0zm10 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0V4.9l-3.613 4.417a.5.5 0 0 1-.74.037L7.06 6.767l-3.656 5.027a.5.5 0 0 1-.808-.588l4-5.5a.5.5 0 0 1 .758-.06l2.609 2.61L13.445 4H10.5a.5.5 0 0 1-.5-.5z"/>
            </svg>
            <a class="nav-link" style="color: white !important;" href="{% url 'core:dashboard-cas' %}">Data Analytics<span class="sr-only">(current)</span></a>
          </div>
        </li>
        {% endif %}
        <!-- {% if request.user.profile.dpt == 'DPT RECHERCHES ET INDEMNISATION DES BAGAGES' %}
        <li class="nav-item active ml-4">
          <div class="d-flex flex-row d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="#d2d2d2" class="bi bi-bag-fill" viewBox="0 0 16 16">
              <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5z"/>
            </svg>
            <a class="nav-link" style="color: white !important;" href="{% url 'core:luggage-view' opt='ahl' %}">Bagages <span class="sr-only">(current)</span></a>
          </div>
        </li>
        {% endif %} -->
        {% if request.user.profile.dpt == 'DPT CONTRATS ET ASSISTANCE AU SOL' or request.user.profile.poste == 'SOUS DIRECTEUR GESTION DES ESCALES'%}
        <li class="nav-item ml-4">
          <div class="d-flex flex-row d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="#d2d2d2" class="bi bi-credit-card-2-back-fill" viewBox="0 0 16 16">
              <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v5H0V4zm11.5 1a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h2a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-2zM0 11v1a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-1H0z"/>
            </svg>
            <a class="nav-link" style="color: white !important;" href="{% url 'core:fact-regular' %}">Facturation<span class="sr-only">(current)</span></a>
          </div>
        </li>
        <li class="nav-item ml-4">
          <div class="d-flex flex-row d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="#d2d2d2" class="bi bi-tags-fill" viewBox="0 0 16 16">
              <path d="M2 2a1 1 0 0 1 1-1h4.586a1 1 0 0 1 .707.293l7 7a1 1 0 0 1 0 1.414l-4.586 4.586a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 2 6.586V2zm3.5 4a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z"/>
              <path d="M1.293 7.793A1 1 0 0 1 1 7.086V2a1 1 0 0 0-1 1v4.586a1 1 0 0 0 .293.707l7 7a1 1 0 0 0 1.414 0l.043-.043-7.457-7.457z"/>
            </svg>
            <a class="nav-link" style="color: white !important;" href="{% url 'core:price-list-actual' %}">Price List <span class="sr-only">(current)</span></a>
          </div>
        </li>
        {% endif %}
        <!-- <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
            <button class="dropdown-item" type="button">Action</button>
            <button class="dropdown-item" type="button">Another action</button>
            <button class="dropdown-item" type="button">Something else here</button>
          </div>
        </div> -->
        <li class="nav-item ml-4 d-flex align-items-center">
          <div class="v1"></div>
        </li>
        <li class="nav-item ml-4 dropdown">
          <a class="nav-link dropdown-toggle" id="usr" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white !important;" href="{{request.user.profile.get_absolute_url}}"> {{request.user.first_name|upper|add:' '|add:request.user.last_name}} </a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenu2" style="background-color: #2e6fa5 !important;">
            <a href="#" class="dropdown-item dwn py-3 mb-0 h5" type="button">PROFILE</a>
            <a href="{% url 'account_logout' %}?next=/accounts/login/" class="dropdown-item dwn py-3 mb-0 h5" type="button">LOGOUT</a>
          </div>
        </li>
        <!-- <li class="nav-item ml-4">
          <a class="nav-link waves-effect" style="color: black !important;" href="{% url 'account_logout' %}?next=/accounts/login/">
            <span class="clearfix d-none d-sm-inline-block"> Logout </span>
          </a>
        </li> -->
        {% else %}
        <li class="nav-item ml-4">
          <a class="nav-link waves-effect" style="border: 1px white solid !important; border-radius: 4px;" href="{% url 'account_login' %}">
            <span class="clearfix d-none d-sm-inline-block"> Login </span>
          </a>
        </li>
        <li class="nav-item ml-4">
          <a class="nav-link waves-effect" style="border-radius: 4px; background-color: white; color:#0e385b !important ;" href="{% url 'account_signup' %}">
            <span class="clearfix d-none d-sm-inline-block"> Signup </span>
          </a>
        </li>
        {% endif %}
        <!-- <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li> -->
      </ul>
    </b>
  </div>
</nav>
{% if request.user.is_authenticated %}
<nav id='navbar_2' class="navbar navbar-expand-lg px-5 py-0 mb-4 " style="background-color: #2e6fa5 !important; color: white;">
  <div class="row">
    <a class="col-sm" href="{% url 'core:get-back' %}">
      <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="white" class="bi bi-chevron-left font-weight-bold" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
      </svg>
    </a>
    <b class="col-auto font-weight-bold" id="title" style="color: white !important; font-weight: bolder; font-size: larger;">&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{title}}</b>
  </div>
  
  <div class="collapse navbar-collapse flex-row-reverse" id="navbarSupportedContent">
    <form class="form-inline my-2 my-lg-1 p-2 w-50">
      <input id="search_navb" class="form-control search mr-sm-2 w-100" type="search" placeholder="Search ..." aria-label="Search" style="background-color: #64ade8 !important; color: white !important; border: none !important;">
      <!-- <button class="btn btn-outline-light my-3 my-sm-0" style="background-color: #B01212 !important;" type="submit">Search</button> -->
    </form>
  </div>
</nav>
{% endif %}