core/urls.py
from django.urls import path
from .views import (
    home_view,
    get_back,
    RequestSummary,
    FlightOccas,
    add_vol_occas_view,
    valid_company,
    AddVolOccas,
    valid_date,
    agent_flight_summary,
    post_vol,
    valid_services,
    validReleveTouchee,
    facturation_occas,
    CompaniesSummary,
    add_company,
    ValidNewCompany,
    valid_new_company_name,
    CompanyDetail,
    valid_fiche,
    price_list,
    price_list_actual,
    ValidPriceList,
    FichesTouchee,
    gestion_affect_fiches,
    AddQuota,
    valid_affect_quota,
    HistQuota,
    AffectQuota,
    valid_escale,
    HistAffect,
    valid_cnl_fiche,
    CNLFiches,
    HistCNL,
    valid_uniq_flt,
    add_schedule,
    NewSchedule,
    FactRegular,
    valid_company_fact,
    dashboard,
    build_chart,
    HistRegularFact,
    validFactRegular,
    FactRegularDetail,
    HistOPCompany,
    luggage_view,
    add_ahl, add_dpr, add_ohd,
    validBagCase,
    BagCaseDetails,
    valid_case,
    HistIndemn,
    AllPriceList,
    ExchangeRates,
    validExchRate,
    fact_regular_bill,
    Dash,
    cas_build_pie_chart,
    cas_build_time_chart,
)

app_name = 'core'

urlpatterns = [
    path('', home_view, name='home-view'),
    path('get-back', get_back, name = 'get-back'),
    path('request-summary/<str:activite>/', RequestSummary.as_view(), name = 'request-summary'),
    path('request-summary/<str:activite>/<str:qs>/', RequestSummary.as_view(), name = 'request-summary-specials'),
    path('flight-detail/<slug>/', FlightOccas.as_view(), name = 'flight-detail'),
    path('add-occas-flight/', add_vol_occas_view, name = 'add-occas-flight'),
    path('valid-company/', valid_company, name = 'valid-company'),
    path('valid-date/', valid_date, name = 'valid-date'),
    path('valid-vol-occas/', AddVolOccas.as_view(), name = 'valid-vol-occas'),
    path('agent-summary/<str:activite>/', agent_flight_summary.as_view(), name='agent-summary'),
    path('post-vol/<slug>/', post_vol.as_view(), name = 'post-vol'),
    path('valid-services/', valid_services, name = 'valid-services'),
    path('valid-releve-touchee/', validReleveTouchee.as_view(), name = 'valid-releve-touchee'),
    path('facturation-occas/<int:n_field>/', facturation_occas, name = 'facturation-occas'),
    path('companies-summary/', CompaniesSummary.as_view(), name = 'companies-summary'),
    path('add-company/', add_company, name = 'add-company'),
    path('valid-new-company/', ValidNewCompany.as_view(), name = 'valid-new-company'),
    path('valid-new-company-name/', valid_new_company_name, name = 'valid-new-company-name'),
    path('compagnie-detail/<slug>/', CompanyDetail.as_view(), name = 'compagnie-detail'),
    path('valid-fiche/', valid_fiche, name = 'valid-fiche'),
    path('price-list/<pk>/', price_list.as_view(), name = 'price-list'),
    path('price-list/', price_list_actual, name = 'price-list-actual'),
    path('annuaire-prices-list/', AllPriceList.as_view(), name = 'annuaire-prices-list'),
    path('valid-price-list/', ValidPriceList.as_view(), name = 'valid-price-list'),
    path('fiche-touchee/', FichesTouchee.as_view(), name = 'fiche-touchee'),
    path('fiche-touchee/gestion-fiches/', gestion_affect_fiches, name = 'gestion-fiches'),
    path('fiche-touchee/gestion-fiches/add-quota/', AddQuota.as_view(), name = 'add-quota'),
    path('valid-affect-quota/', valid_affect_quota, name = 'valid-affect-quota'),
    path('fiche-touchee/gestion-fiches/hist-quota/', HistQuota.as_view(), name = 'hist-quota'),
    path('affect-quota/', AffectQuota.as_view(), name = 'affect-quota'),
    path('valid-escale/', valid_escale, name = 'valid-escale'),
    path('fiche-touchee/gestion-fiches/hist-affect/', HistAffect.as_view(), name = 'hist-affect'),
    path('valid-cnl-fiche/', valid_cnl_fiche, name = 'valid-cnl-fiche'),
    path('fiche-touchee/gestion-fiches/cnl-fiches/', CNLFiches.as_view(), name = 'cnl-fiches'),
    path('fiche-touchee/gestion-fiches/hist-cnl/', HistCNL.as_view(), name = 'hist-cnl'),
    path('valid-uniq-flt/', valid_uniq_flt, name = 'valid-uniq-flt'),
    path('add-schedule/', add_schedule, name = 'add-schedule'),
    path('new-schedule/', NewSchedule.as_view(), name = 'new-schedule'),
    path('fact-regular/', FactRegular.as_view(), name = 'fact-regular'),
    path('valid-company-fact/', valid_company_fact, name = 'valid-company-fact'),
    path('dashboard/', dashboard, name = 'dashboard'),
    path('dashboard-cas/', Dash, name = 'dashboard-cas'),
    path('dashboard/build-chart/', build_chart, name = 'build-chart'),
    path('fact-regular/hist-regular-fact/', HistRegularFact.as_view(), name = 'hist-regular-fact'),
    path('valid-fact-regular/', validFactRegular.as_view(), name = 'valid-fact-regular'),
    path('fact-regular-detail/<slug>/', FactRegularDetail.as_view(), name = 'fact-regular-detail'),
    path('compagnie-detail/<slug>/historic-operations-company/', HistOPCompany.as_view(), name = 'historic-operations-company'),
    path('luggage-summary/<str:opt>/', luggage_view.as_view(), name = 'luggage-view'),
    path('luggage-view/add-ahl/', add_ahl, name = 'add-ahl'),
    path('luggage-view/add-dpr/', add_dpr, name = 'add-dpr'),
    path('luggage-view/add-ohd/', add_ohd, name = 'add-ohd'),
    path('bag-case/<pk>/', BagCaseDetails.as_view(), name = 'bag-case-details'),
    path('valid-bag-case/', validBagCase.as_view(), name = 'valid-bag-case'),
    path('valid-case/', valid_case, name = 'valid-case'),
    path('bag-case/<pk>/historique-des-propositions/', HistIndemn.as_view(), name = 'historique-des-propositions'),
    path('exchange-rates/', ExchangeRates.as_view(), name = 'exchange-rates'),
    path('valid-exchange-rate/', validExchRate.as_view(), name = 'valid-exchange-rate'),
    path('fact-regular-bill/<int:id>/', fact_regular_bill.as_view(), name = 'fact-regular-bill'),
    path('cas-build-pie-chart/', cas_build_pie_chart, name = 'cas-build-pie-chart'),
    path('cas-build-time-chart/', cas_build_time_chart, name = 'cas-build-time-chart'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('allauth.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView, ListView, View
from django.http import HttpRequest, HttpResponse, JsonResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.db.models import Max, Min, Sum, Q
from django.shortcuts import reverse
from django.contrib import messages
from sqlalchemy import create_engine
import datetime
from django.utils import timezone
from django.utils.safestring import mark_safe
from .CONST import *
from .ssim import ssim_df
from django.db.models.fields import BLANK_CHOICE_DASH
from django.template.loader import render_to_string
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.core.serializers import serialize
from django.utils.text import slugify
import calendar
import pandas as pd
import numpy as np
import json
import re
from django_pandas.io import read_frame
from .models import (
    FLIGHT_ASSIST,
    FLIGHT_OCCAS,
    COMP_DISPATCHER,
    FLIGHT_FI,
    FICHE_TOUCHEE,
    TARIF_OCCAS,
    EXCHANGE,
    ESCALES,
    HISTORIQUE_ADD_QUOTA,
    HISTORIQUE_AFFECT_QUOTA,
    HISTORIQUE_CNL_FICHES,
    HISTORIQUE_REGULAR_FACT,
    HISTORIQUE_OP_COMPANY,
    BAG_SUIVI, BAG_ID_CHART, BAG_MRD_TYPE_DMG, BAG_RL, BAG_DETAILS, BAG_FLIGHTS,
    BAG_HIST_INDEMN,
    User,
)
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.utils.html import escape
import requests

escales = ESCALES.objects.all()

# FUNCTIONS ****************************************

def check_holiday_date(obj):
    if obj.assist_jourferie:
        return True
    return False

def assist_night(obj, etat):
    if etat == 'actual':
        if (obj.ata.hour >= datetime.datetime.strptime(NIGHT[0], '%H:%M').hour or obj.ata.hour <= datetime.datetime.strptime(NIGHT[1], '%H:%M').hour) or (obj.atd.hour >= datetime.datetime.strptime(NIGHT[0], '%H:%M').hour or obj.atd.hour <= datetime.datetime.strptime(NIGHT[1], '%H:%M').hour):
            return True
    else:
        if (datetime.datetime.strptime(obj.sta, '%H:%M').hour >= datetime.datetime.strptime(NIGHT[0], '%H:%M').hour or datetime.datetime.strptime(obj.sta, '%H:%M').hour <= datetime.datetime.strptime(NIGHT[1], '%H:%M').hour) or (datetime.datetime.strptime(obj.std, '%H:%M').hour >= datetime.datetime.strptime(NIGHT[0], '%H:%M').hour or datetime.datetime.strptime(obj.std, '%H:%M').hour <= datetime.datetime.strptime(NIGHT[1], '%H:%M').hour):
            return True
    return False

def assist_weekend(obj, etat):
    if etat == 'actual':
        if obj.act_dte_arr.weekday() == 4 or obj.act_dte_arr.weekday() == 5 or obj.act_dte_dep.weekday() == 4 or obj.act_dte_dep.weekday() == 5:
            return True
    else:
        # print(obj.date_arrivee, datetime.datetime.strptime(obj.date_arrivee, '%Y-%m-%d').weekday())
        if datetime.datetime.strptime(obj.date_arrivee, '%Y-%m-%d').weekday() == 4 or datetime.datetime.strptime(obj.date_arrivee, '%Y-%m-%d').weekday() == 5 or datetime.datetime.strptime(obj.date_depart, '%Y-%m-%d').weekday() == 4 or datetime.datetime.strptime(obj.date_depart, '%Y-%m-%d').weekday() == 5:
            return True
    return False

def assist_standby(obj, etat):
    if etat == 'actual':   
        # act_dte_dep = datetime.datetime.strptime(obj.act_dte_dep, '%Y-%m-%d')
        # atd = datetime.datetime.strptime(obj.atd, '%H:%M')
        # act_dte_arr = datetime.datetime.strptime(obj.act_dte_arr, '%Y-%m-%d')
        # ata = datetime.datetime.strptime(obj.ata, '%H:%M')
        if datetime.datetime.combine(obj.act_dte_dep, obj.atd) - datetime.datetime.combine(obj.act_dte_arr, obj.ata) >= datetime.timedelta(hours=6):
            return True
    else:
        sta = datetime.datetime.strptime(obj.sta, '%H:%M')
        std = datetime.datetime.strptime(obj.std, '%H:%M')
        date_depart = datetime.datetime.strptime(obj.date_depart, '%Y-%m-%d')
        date_arrivee = datetime.datetime.strptime(obj.date_arrivee, '%Y-%m-%d')
        if datetime.datetime.combine(date_depart.date(), std.time()) - datetime.datetime.combine(date_arrivee.date(), sta.time()) >= datetime.timedelta(hours=6):
            return True
    return False

def get_absence_demande_peno(obj):
    comp = TARIF_OCCAS.objects.get(dte_begin__lte = obj.act_dte_arr, dte_end__gte = obj.act_dte_arr)
    if datetime.datetime.combine(obj.date_arrivee, obj.sta) - datetime.datetime.combine(obj.date_demande, obj.heure_demande) < datetime.timedelta(hours=24):
        return True
    return False

def check_retard(obj):
    # act_dte_arr = datetime.datetime.strptime(obj.act_dte_arr, '%Y-%m-%d')
    # ata = datetime.datetime.strptime(obj.ata, '%H:%M')
    # sta = datetime.datetime.strptime(obj.sta, '%H:%M')
    # date_arrivee = datetime.datetime.strptime(obj.date_arrivee, '%Y-%m-%d')
    if datetime.datetime.combine(obj.act_dte_arr, obj.ata) - datetime.datetime.combine(obj.date_arrivee, obj.sta) > datetime.timedelta(hours=5):
        return 50
    elif datetime.datetime.combine(obj.act_dte_arr, obj.ata) - datetime.datetime.combine(obj.date_arrivee, obj.sta) > datetime.timedelta(hours=3):
        return 30
    elif datetime.datetime.combine(obj.act_dte_arr, obj.ata) - datetime.datetime.combine(obj.date_arrivee, obj.sta) > datetime.timedelta(hours=1):
        return 15
    return 0

def get_tarif_de_base(obj):
    comp = COMP_DISPATCHER.objects.get(company_dispatcher=obj.compagnie_dispatcher)
    if comp.activite == 'OCCASIONNEL':
        if obj.act_dte_arr is not None:
            comp = TARIF_OCCAS.objects.get(dte_begin__lte = obj.act_dte_arr, dte_end__gte = obj.act_dte_arr)
        else:
            comp = TARIF_OCCAS.objects.get(dte_begin__lte = obj.date_arrivee, dte_end__gte = obj.date_arrivee)
    tarif_base = 0
    # MTOW - NATURE TOUCHEE ------------------------------------------------------------------------------>
    if float(obj.mtow_tonnes_field) <= 10:
        if obj.nature_touchee == 'TECH':
            tarif_base += (comp.MTOW_10_TECH)
        else:
            tarif_base += (comp.MTOW_10_COM)
    elif float(obj.mtow_tonnes_field) <= 30:
        if obj.nature_touchee == 'TECH':
            tarif_base += (comp.MTOW_10_30_TECH)
        else:
            tarif_base += (comp.MTOW_10_30_COM)
    elif float(obj.mtow_tonnes_field) <= 50:
        if obj.nature_touchee == 'TECH':
            tarif_base += (comp.MTOW_30_50_TECH)
        else:
            tarif_base += (comp.MTOW_30_50_COM)
    elif float(obj.mtow_tonnes_field) <= 80:
        if obj.nature_touchee == 'TECH':
            tarif_base += (comp.MTOW_50_80_TECH)
        else:
            tarif_base += (comp.MTOW_50_80_COM)
    elif float(obj.mtow_tonnes_field) <= 150:
        if obj.nature_touchee == 'TECH':
            tarif_base += (comp.MTOW_80_150_TECH)
        else:
            tarif_base += (comp.MTOW_80_150_COM)
    elif float(obj.mtow_tonnes_field) <= 250:
        if obj.nature_touchee == 'TECH':
            tarif_base += (comp.MTOW_150_250_TECH)
        else:
            tarif_base += (comp.MTOW_150_250_COM)
    else:
        if obj.nature_touchee == 'TECH':
            tarif_base += (comp.MTOW_250_TECH)
        else:
            tarif_base += (comp.MTOW_250_COM)
    return tarif_base

def get_extra_services_tarif(obj):
    comp = COMP_DISPATCHER.objects.get(company_dispatcher=obj.compagnie_dispatcher)
    if comp.activite == 'OCCASIONNEL':
        if obj.act_dte_arr is not None:
            comp = TARIF_OCCAS.objects.get(dte_begin__lte = obj.act_dte_arr, dte_end__gte = obj.act_dte_arr)
        else:
            comp = TARIF_OCCAS.objects.get(dte_begin__lte = obj.date_arrivee, dte_end__gte = obj.date_arrivee)
    extra_service = 0
    extra_service = (obj.ASSIST_UM * (comp.ASSIST_UM)) + (obj.ASSIST_WCH * (comp.ASSIST_WCH)) + (obj.ASSIST_TRANSIT * (comp.ASSIST_TRANSIT)) + \
    (obj.ACC_SALON * (comp.ACC_SALON)) + (obj.ASSIST_VIP * (comp.ASSIST_VIP)) + (obj.USE_DCS * (comp.USE_DCS)) + (obj.DEPORTEE * (comp.DEPORTEE)) + \
    (obj.AGENT_SERV_PASSAGE * (comp.AGENT_SERV_PASSAGE)) + (obj.CIVIERE * (comp.CIVIERE)) + (obj.HUM * (comp.HUM)) + (obj.OUV_DOSS_BAG * (comp.OUV_DOSS_BAG)) + \
    (obj.DOSS_VOL_IMP * (comp.DOSS_VOL_IMP)) + (obj.AGENT_COORD * (comp.AGENT_COORD)) + (obj.COMM_SOL_COCKPIT * (comp.COMM_SOL_COCKPIT)) + \
    (obj.AGENT_OP_QUALIF * (comp.AGENT_OP_QUALIF)) + (round((obj.GPU / 60), 2) * (comp.GPU)) + (obj.ACU * (comp.ACU)) + (obj.RECONC_BAG_BRS * (comp.RECONC_BAG_BRS)) + \
    (obj.PASSERELLE_PSG * (comp.PASSERELLE_PSG)) + (obj.CAMION_ELEV * (comp.CAMION_ELEV)) + (obj.VIP_BUS * (comp.VIP_BUS)) + (obj.VEHICULE_TRANSP_PISTE * (comp.VEHICULE_TRANSP_PISTE)) + \
    (obj.PUSH_BACK * (comp.PUSH_BACK)) + (obj.TOWING * (comp.TOWING)) + (obj.CHARIOT_BAG * (comp.CHARIOT_BAG)) + (obj.TRACT_CHARIOT * (comp.TRACT_CHARIOT)) + \
    (obj.TAPIS_BAG * (comp.TAPIS_BAG)) + (obj.PLATEFORME * (comp.PLATEFORME)) + (obj.PORTE_CONTAINER_PALETTE * (comp.PORTE_CONTAINER_PALETTE)) + \
    (obj.CONTAINER_PALETTE * (comp.CONTAINER_PALETTE)) + (obj.ELEV_FOURCHE * (comp.ELEV_FOURCHE)) + (obj.AGENT_SERV_PISTE * (comp.AGENT_SERV_PISTE)) + \
    (obj.DB_MANIP_ULD * (comp.DB_MANIP_ULD))
    if obj.capacite < 200:
        extra_service += (obj.ASU * (comp.ASU_MOY_PORT)) + (obj.VIDE_TOILET * (comp.VIDE_TOILET_MOY_PORT)) + (obj.PLEIN_WATER * (comp.PLEIN_WATER_MOY_PORT))
    else:
        extra_service += (obj.ASU * (comp.ASU_BIG_PORT)) + (obj.VIDE_TOILET * (comp.VIDE_TOILET_BIG_PORT)) + (obj.PLEIN_WATER * (comp.PLEIN_WATER_BIG_PORT)) + (obj.ID_BAG * (comp.ID_BAG_200))
    if obj.capacite <= 100:
        extra_service += (obj.NET_CABINE * (comp.NET_CABINE_100)) + (obj.ARRANGEMENT_CAB * (comp.ARRANGEMENT_CAB_100))
    elif obj.capacite <= 200:

core/templates/core/fact_regular.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load cart_template_tags %}

{% block head_title %}
Facturation des vols réguliers
{% endblock head_title %}

{% block content %}

<div id="message_err" class="mt-2 pb-0 pt-0" style="display: none;">
    <div id="alert_err" class="alert alert-danger alert-dismissible fade show" role="alert">
    </div>
</div>

{% if 'COMPAGNIE' not in title %}
<form method="POST" action="{% url 'core:valid-fact-regular' %}" class="form">
    {% csrf_token %}
    <div class="shadow p-3 mb-4 bg-white rounded w-100y">
        <h3 class="mb-4" style="font-weight: bolder !important;"><b>FACTURATION DES VOLS RÉGULIERS</b></h3>
        <a href="{% url 'core:hist-regular-fact' %}" class="mt-5 h5" target="_blank" style="color: grey !important;"><u>Consulter l'historique des facturations</u></a>
        <div id="msg_last_fact" class="mt-2 pb-0 pt-0" style="display: none;">
            <div id="alert_last_fact" class="fade show" role="alert">
            </div>
        </div>
        <!-- <a href="{% url 'core:hist-cnl' %}" class="mt-5 h5" target="_blank" style="color: grey !important;"><u>Consulter l'historique des annulations</u></a> -->
        <div class="mt-4 form-row">
            <div class="form-group col-md-3">
                <label for="compagnie_dispatcher" class="col-form-label">Escale</label>
                <select class="custom-select chg" name="escale" id="escale" required>
                    {% for esc in escales %}
                    {% if esc|get_type == "<class 'tuple'>" %}
                        <option value="all">{{esc.1}}</option>
                    {% else %}
                    <option value="{{esc.escale}}">{{esc.escale}} - {{esc.full_name}}</option>
                    {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="form-group col-md-2">
                <label for="compagnie_dispatcher" class="col-form-label">Compagnie</label>
                <select class="custom-select chg" name="compagnie_dispatcher" id="compagnie_dispatcher" disabled required>
                    {% for p in companies %}
                    {% if p|get_type == "<class 'tuple'>" %}
                        <option value="all">{{p.1}}</option>
                    {% else %}
                    <option value="{{p}}">{{p}}</option>
                    {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="form-group col-md-2">
                <label for="from_date" class="col-form-label">À partir du</label>
                <input type="date" max="2999-12-31" class="form-control chg" name="from_date" id="from_date" readonly>
            </div>
            <div class="form-group col-md-2">
                <label for="until_date" class="col-form-label">Jusqu'au</label>
                <input type="date" max="2999-12-31" class="form-control chg" name="until_date" id="until_date" readonly>
            </div>
            <!-- <div class="d-flex align-items-center">
                
            </div> -->
        </div>
    </div>
    <button type="submit" id="submit-form" class="btn mt-2" style="color: white !important; background-color: #0e385b !important;" disabled><b class="h6">GÉNÉRER LA FACTURE</b></button>
</form>
{% endif %}

<script>
    $('#escale').on('change', function(){
        if($('#escale').val() != "('', '---------')"){
            $('#compagnie_dispatcher').prop('disabled', false)
        }
        else{
            $('#compagnie_dispatcher').prop('disabled', true)
        }
    });

    $('.chg').on('change', function(){
        var comp;
        var chg = false
        $('.chg').each(function(){
            if( $(this).val() == 'all' || $(this).val() == '' ){
                chg = true
            }
        });
        if(!chg){
            $('#submit-form').prop('disabled', false)
        }
        else{
            $('#submit-form').prop('disabled', true)
        }
        if($('#compagnie_dispatcher').val() != "('', '---------')"){
            $('#from_date').prop('readonly', false);
            $('#until_date').prop('readonly', false);
            // $('#submit-form').prop('disabled', false);
            comp = $('#compagnie_dispatcher').val();
        }
        else{
            $('#from_date').prop('readonly', true);
            $('#from_date').val('');
            $('#until_date').prop('readonly', true);
            $('#until_date').val('');
            // $('#submit-form').prop('disabled', true);
            comp = '';
        }
        data = {'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
        'compagnie_dispatcher' : comp,
        'from_date' : $('#from_date').val(),
        'until_date' : $('#until_date').val(),
        'escale': $('#escale').val()};
        $.ajax({
            type:'POST',
            url:'{% url "core:valid-company-fact" %}',
            datatype: 'JSON',
            data: data,
            success: function(data){
                if(data.exist){
                    if(data.msg.startsWith('Une partie')){
                        $('#type_fact').show();
                    }
                    else{
                        $('#type_fact').hide();
                    }
                    // $('#submit-form').prop('disabled', true);
                    if($('#alert_last_fact').children().length > 0){
                        $('#alert_last_fact').find('.msg').remove();
                        $('#msg_last_fact').slideToggle("slow");
                    }
                    if($('#alert_err').children().length > 0){
                        $('#alert_err').find('.msg').remove();
                        $('#alert_err').append('<p class="msg"><b>' + data.msg + '</b></p>');
                    }
                    else{
                        $('#alert_err').append('<p class="msg"><b>' + data.msg + '</b></p>');
                        $('#message_err').slideToggle("slow");
                    }
                }
                else{
                    if($('#alert_err').children().length > 0){
                        $('#alert_err').find('.msg').remove();
                        $('#message_err').slideToggle("slow");
                        if($('#from_date').val() != '' && $('#until_date').val() != ''){
                            $('#submit-form').prop('disabled', false);
                        }
                    }
                    if(data.msg != 'XXX' ){
                        if($('#alert_last_fact').children().length > 0){
                            $('#alert_last_fact').find('.msg').remove();
                            $('#alert_last_fact').append('<p class="msg h6 text-muted text-success"><b>La dernière facturation effectuée pour ' + data.comp + ' pour l\'escale ' + data.esc + ' : ' + data.date_from + ' au ' + data.date_until + '</b></p>');
                        }
                        else{
                            $('#alert_last_fact').append('<p class="msg h6 text-muted text-success"><b>La dernière facturation effectuée pour ' + data.comp + ' pour l\'escale ' + data.esc + ' : ' + data.date_from + ' au ' + data.date_until + '</b></p>');
                            $('#msg_last_fact').slideToggle("slow");
                        }
                    }
                }
            }
        });
    });
</script>


{% endblock content %}